name: HyperBian release

on:
  repository_dispatch:
    types: [hyperion_push]

jobs:
  rpi-image:
    name: "Build HyperBian image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils quilt parted qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc

      # build image
      - name: Build HyperBian
        run: |
          git clone https://github.com/RPi-Distro/pi-gen.git
          touch ./pi-gen/stage3/SKIP ./pi-gen/stage4/SKIP ./pi-gen/stage4/SKIP_IMAGES
          touch ./pi-gen/stage5/SKIP ./pi-gen/stage5/SKIP_IMAGES
          cp -R stage-hyperbian pi-gen/stage-hyperbian
          cp config pi-gen/config && cd pi-gen
          sudo ./build.sh
          sudo mv ./deploy/*.zip ./deploy/HyperBian.zip
          sudo chown -fR $(stat -c "%U:%G" .) ./deploy

      - name: Delete previous HyperBian Release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # create release and upload image
      - name: Create release and upload image
        uses: svenstaro/upload-release-action@2.4.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pi-gen/deploy/HyperBian.zip
          asset_name: HyperBian.zip
          tag: HyperBian
          release_name: HyperBian
          body: "Raspberry Pi OS Lite with [Hyperion](https://github.com/hyperion-project/hyperion.ng) pre installed. Also called HyperBian."
          overwrite: true
